### ISSUE TITLE
How to run unit tests? 

### ISSUE THREAD

**Issue by kiptoomm** [justanr/marshmallow_enum#18]
Hi @justanr 

Neat light library. 

I was hoping to start making contributions. It's a noobish question, but how do I go about running tests? I tried the following from the root dir of marshmallow_enum/ but ran into import errors. I'm wondering if there's something wrong with my setup... 

>(venv) $ pytest tests/test_enum_field.py
 ImportError while importing test module '~/dev/projects/frameworks/marshmallow_enum/tests/test_enum_field.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
venv/lib/python2.7/site-packages/_pytest/python.py:395: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
venv/lib/python2.7/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
venv/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:212: in load_module
    py.builtin.exec_(co, mod.__dict__)
tests/test_enum_field.py:12: in <module>
    from marshmallow_enum import EnumField
E   ImportError: No module named marshmallow_enum
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

And in general, it'd be great if you can add a section on how to contribute :)

**Comment by justanr** [comment]
Adding those sections is a good idea. :thumbsup:

To run the tests, you should install tox and run it in the directory that you cloned the source to
