### ISSUE TITLE
Provide pypi package

### ISSUE THREAD

**Issue by Tim-Erwin** [justanr/marshmallow_enum#2]
Thanks for this project. Could you please upload a package on pypi for that?

**Comment by justanr** [comment]
mfw i didn't actually do that. When I get home from work I can do this. I need to release updates for a few of my other packages, too.

**Comment by justanr** [comment]
Check it out! https://pypi.python.org/pypi/marshmallow-enum/1.0

**Comment by Tim-Erwin** [comment]
Wonderful, thanks.
