### ISSUE TITLE
cast value type if load by value

### ISSUE THREAD

**Issue by sanzoghenzo** [justanr/marshmallow_enum#33]
I'm starting to use this cool package in my little REST API service that uses flask_marshmallow/webargs for request validation.

I have integer values in my enums, and before introducing EnumField I used fields.Integer to automatically cast the value in the json request (and then manually load the enum).

If I use by_value=True, marshmallow complains that the value provided is not valid, because it's still a json string.

I've managed to solve the problem by introspecting the enum on __init__:

```python
class EnumField(Field):
    def __init__(
            self, enum, by_value=False, load_by=None, dump_by=None, error='', *args, **kwargs
    ):
        # ...
        self.dump_by = dump_by

        self.num_type = None
        if self.load_by == LoadDumpOptions.value:
            types = tuple(set(type(x.value) for x in self.enum))
            if len(types) == 1 and types[0] in (int, float):
                self.num_type = types[0]

        super(EnumField, self).__init__(*args, **kwargs)
```

then try the conversion in `_deserialize_by_value`:

```python
    def _deserialize_by_value(self, value, attr, data):
        try:
            return self.enum(value)
        except ValueError:
            if self.num_type:
                try:
                    return self.enum(self.num_type(value))
                except (ValueError, TypeError):
                    self.fail('by_value', input=value, value=value)
            self.fail('by_value', input=value, value=value)
```

Maybe there's a cleaner way to do the introspection...

**Comment by petrus-v** [comment]
Reading issue here...

I've the filling it should not be the matter of this library, I would suggest to use [pre_load decorator](https://marshmallow.readthedocs.io/en/stable/api_reference.html#marshmallow.decorators.pre_load) to cast the string into integer or use string value in your Enum.

**Comment by sanzoghenzo** [comment]
My bad, I realized that in my unit tests I was passing the test data as a form instead of JSON, so the value was converted to string.

Thanks for the input @petrus-v , your input made me look in the right direction!
