### ISSUE TITLE
Allow custom error message as with OneOf validator

### ISSUE THREAD

**Issue by vlcinsky** [justanr/marshmallow_enum#4]
`marsmallow.validate.OneOf` has `error` parameter allowing to customize error message with interpolation for `{input}`, `{choices}` and `{labels}`.

Testing schema with `EnumFields` shows, error messages are ignored and printed always in the same manner.

It would be nice to allow `EnumField` supporting the same parameter for interpolation with `{input}` and `{choices}`.

**Comment by justanr** [comment]
I'm not sure when I'd be able to get to this, but I'll happily consider a PR. Definitely a +1

**Comment by justanr** [comment]
@vlcinsky Checkout #5 for an implementation of this

**Comment by vlcinsky** [comment]
@justanr Tested, works very well. Well done.
Thanks a lot.
