### ISSUE TITLE
Warning msg from marshmallow on raising enum failure

### ISSUE THREAD

**Issue by anordin95** [justanr/marshmallow_enum#43]
How to reproduce:

`a.py`
```
from dataclasses import asdict
import marshmallow_dataclass
import pytest

from enum import Enum

class Animal(Enum):
    DOG = 1
    CAT = 2

@marshmallow_dataclass.dataclass
class Pet:
    pet_type: Animal

def test_run():
    pet = Pet(pet_type="car") # not an Animal
    errors = pet.Schema().validate(asdict(pet))

```

`pytest a.py`

![image](https://user-images.githubusercontent.com/7705027/94312881-bb67e600-ff4b-11ea-883c-061bff00f5bd.png)

I'm not sure why, but the warning is only surfaced when executing this with `pytest`.

The warning is raised in `marshmallow` here: https://github.com/marshmallow-code/marshmallow/blob/51c4b6c30824551d10824c52fee3c42bfaedf0cc/src/marshmallow/fields.py#L273

**Comment by justanr** [comment]
Closed by #44
