### ISSUE TITLE
Validation/required not implemented

### ISSUE THREAD

**Issue by layoaster** [justanr/marshmallow_enum#7]
Following your README sample, I could see that when using `by_value=True` there is no validations when loading data so I could do the following:

```
UserSchema().load({'username': 'justanr', 'permission_level': 5}).data
# {'username': 'justanr'}
```
The field got omitted  even though I marked the `permission_level` required:

```
class UserSchema(Schema):
    permission_level = EnumField(PermissionEnum, by_value=True, required=True)

    class Meta:
        additional = ['username']
```

**Comment by justanr** [comment]
Is this something that should be looked into, or a mistake? Either is fine, just want to be sure.

**Comment by layoaster** [comment]
My mistake. I realized I haven't enabled the `strict`mode after opening this thread. Sorry

**Comment by justanr** [comment]
Is cool, wanted to be sure everything was handled. Thanks for checking out this project. :)
